services:
  - type: web
    name: flask-socketio-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:5000 app:app
    region: us
